#!/usr/bin/env python3
"""Rasterize the modern GUI skins' fonts into C++ headers.

The modern skins (ACIDUS_GUI_STYLE=MODERN) print anti-aliased lettering.
Rather than ship font files and a TrueType rasterizer, this script renders
the glyphs the panels need (space..Z) once, offline, into 4-bit alpha
bitmaps at the GUIs' 2x supersampled resolution. ModernDraw's drawText
scales them to other sizes. Two faces:

  LabelFont.hpp    Liberation Sans Bold, slightly condensed like the 303's
                   panel lettering; cap height 7 px (14 at 2x). Labels.
  DisplayFont.hpp  Liberation Sans Regular; cap height 16 px (32 at 2x).
                   Burette's note names, buttons and values.

    python3 tools/gen_gui_fonts.py [fonts dir]

Needs Pillow. Each skin includes only the fonts it uses.
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

FONT_DIR = Path(sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/liberation")
OUT_DIR = Path(__file__).resolve().parent.parent / "src/gui/modern"
OVERSAMPLE = 4     # render bigger, then box-filter down for clean edges
FIRST, LAST = 32, 90

FONTS = [
    # header, C++ name, font file, size (2x px), horizontal squeeze, description
    ("LabelFont.hpp", "kLabelFont", "LiberationSans-Bold.ttf", 20, 0.86, "Liberation Sans Bold"),
    ("DisplayFont.hpp", "kDisplayFont", "LiberationSans-Regular.ttf", 44, 1.0, "Liberation Sans Regular"),
]


def generate(header, cname, fontfile, px, condense, desc):
    font = ImageFont.truetype(str(FONT_DIR / fontfile), px * OVERSAMPLE)
    cap = font.getbbox("H")
    cap_h = round((cap[3] - cap[1]) / OVERSAMPLE)
    cap_top = round(cap[1] / OVERSAMPLE)
    glyphs, data = [], []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch) * condense / OVERSAMPLE * 16)
        bbox = font.getbbox(ch)
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append((len(data), 0, 0, 0, 0, adv))
            continue
        # Pad the box to the oversample grid so the downsample stays aligned.
        x0 = (bbox[0] // OVERSAMPLE) * OVERSAMPLE
        y0 = (bbox[1] // OVERSAMPLE) * OVERSAMPLE
        img = Image.new("L", (bbox[2] - x0 + OVERSAMPLE, bbox[3] - y0 + OVERSAMPLE), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
        w = max(1, round(img.width * condense / OVERSAMPLE))
        h = max(1, img.height // OVERSAMPLE)
        small = img.resize((w, h), Image.BOX)
        bb = small.getbbox()   # trim the padding
        if bb is None:
            glyphs.append((len(data), 0, 0, 0, 0, adv))
            continue
        small = small.crop(bb)
        off_x = round(x0 * condense / OVERSAMPLE) + bb[0]
        off_y = y0 // OVERSAMPLE + bb[1]
        nib = [min(15, (v + 8) // 17) for v in small.tobytes()]
        if len(nib) % 2:
            nib.append(0)
        start = len(data)
        data += [(nib[i] << 4) | nib[i + 1] for i in range(0, len(nib), 2)]
        glyphs.append((start, small.width, small.height, off_x, off_y, adv))

    guard = "ACIDUS_" + header.replace(".", "_").upper()
    ns = cname[1:].lower() + "_data"
    lines = [
        "// Generated by tools/gen_gui_fonts.py -- do not edit.",
        f"// Glyphs rasterized from {desc}, Copyright (c) 2012 Red Hat,",
        "// Inc., with Reserved Font Name Liberation; digitized data (c) 2010 Google",
        "// Corporation. Licensed under the SIL Open Font License 1.1",
        "// (https://openfontlicense.org).",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "gui/modern/ModernDraw.hpp"',
        "",
        "namespace acidus {",
        "namespace modern {",
        f"namespace {ns} {{",
        "",
        "constexpr AtlasGlyph kGlyphs[] = {",
    ]
    for code, g in zip(range(FIRST, LAST + 1), glyphs):
        c = chr(code)
        lines.append(f"    {{{g[0]}, {g[1]}, {g[2]}, {g[3]}, {g[4]}, {g[5]}}},  // '{c if c != chr(92) else 'backslash'}'")
    lines += ["};", "", "constexpr uint8_t kAlpha[] = {"]
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 20]) + ",")
    lines += [
        "};",
        "",
        f"}} // namespace {ns}",
        "",
        f"// {desc}, {px} px at 2x; cap height {cap_h} px at 2x.",
        f"constexpr AtlasFont {cname}{{ {ns}::kGlyphs, {ns}::kAlpha, {FIRST}, {LAST}, {cap_top}, {cap_h} }};",
        "",
        "} // namespace modern",
        "} // namespace acidus",
        "",
        f"#endif // {guard}",
        "",
    ]
    (OUT_DIR / header).write_text("\n".join(lines))
    print(f"wrote {header}: {len(glyphs)} glyphs, {len(data)} bytes, cap height {cap_h}")


for f in FONTS:
    generate(*f)
