#!/usr/bin/env python3
"""Generate src/presets/PresetData.cpp: the built-in presets (spec 05).

    python3 tools/gen_presets.py

* FT / FC factory presets are decoded from docs/reference/cs80_presets.json
  (row volts per hardware tone) with the row->parameter conversions of
  docs/spec/05_PRESETS.md §3.
* The library presets live in tools/preset_library.py as dictionaries of
  parameter keys over the Init patch (doc 04 defaults).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from preset_library import LIBRARY  # noqa: E402

# Row -> (line parameter key, conversion). 'inv' = 1 - V/10, 'lin' = V/10, 'sw' = V >= 5.
ROWS = {
    1: ("pwmSpeed", "lin"), 2: ("pwmDepth", "lin"), 3: ("pw", "lin"), 4: ("square", "sw"),
    5: ("saw", "sw"), 6: ("noise", "lin"), 7: ("hpf", "lin"), 8: ("resH", "inv"),
    9: ("lpf", "lin"), 10: ("resL", "inv"), 11: ("il", "lin"), 12: ("al", "lin"),
    13: ("fegA", "inv"), 14: ("fegD", "inv"), 15: ("fegR", "inv"), 16: ("vcfLevel", "lin"),
    17: ("sine", "lin"), 18: ("vegA", "inv"), 19: ("vegD", "inv"), 20: ("vegS", "lin"),
    21: ("vegR", "inv"), 22: ("level", "lin"), 23: ("initBrill", "lin"), 24: ("initLevel", "lin"),
    25: ("afterBrill", "lin"), 26: ("afterLevel", "lin"),
}

# Tone selector order per channel (spec page, button order).
CHANNEL_TONES = {
    "I": ["String 1", "String 3", "Brass 1", "Flute", "Electric Piano", "Clavichord 1",
          "Harpsichord 1", "Organ 1", "Guitar 1", "Funky 1", "Funky 3"],
    "II": ["String 2", "String 4", "Brass 2", "Brass 3", "Bass", "Clavichord 2",
           "Harpsichord 2", "Organ 2", "Guitar 2", "Funky 2", "Funky 4"],
}


def decode_tone(volts):
    out = {}
    for row, (key, conv) in ROWS.items():
        v = float(volts.get(str(row), 0.0))
        if conv == "lin":
            x = v / 10.0
        elif conv == "inv":
            x = 1.0 - v / 10.0
        else:
            x = 1.0 if v >= 5.0 else 0.0
        out[key] = round(min(max(x, 0.0), 1.0), 4)
    return out


def line_dict(prefix, tone):
    return {f"{prefix}.{k}": v for k, v in tone.items()}


def factory_presets():
    data = json.loads((ROOT / "docs/reference/cs80_presets.json").read_text())
    tones = {}
    for ch, names in CHANNEL_TONES.items():
        for name in names:
            tones[(ch, name)] = decode_tone(data["channels"][ch][name]["volts"])
    ft, fc = [], []
    for ch, names in CHANNEL_TONES.items():
        prefix, other = ("l1", "l2") if ch == "I" else ("l2", "l1")
        for name in names:
            vals = line_dict(prefix, tones[(ch, name)])
            vals[f"{other}.level"] = 0.0
            vals["mix"] = 0.5
            ft.append((f"FT {name}", vals))
    for a, b in zip(CHANNEL_TONES["I"], CHANNEL_TONES["II"]):
        vals = line_dict("l1", tones[("I", a)])
        vals.update(line_dict("l2", tones[("II", b)]))
        vals["detune"] = 0.2
        vals["mix"] = 0.5
        na, nb = a.split(" "), b.split(" ")
        if len(na) == 2 and len(nb) == 2 and na[0] == nb[0]:
            label = f"{na[0]} {na[1]}+{nb[1]}"
        elif a.startswith("Electric"):
            label = f"E.Piano+{b}"
        else:
            label = f"{a}+{b}"
        fc.append((f"FC {label}", vals))
    return ft, fc


def valid_keys():
    """Parameter keys from src/core/Params.cpp (line keys get l1./l2.)."""
    import re
    src = (ROOT / "src/core/Params.cpp").read_text()
    line_block = src[src.index("kLine[LP_COUNT]"):src.index("kGlobal[")]
    glob_block = src[src.index("kGlobal["):src.index("struct Table")]
    keys = set()
    for k in re.findall(r'\{ "([A-Za-z]+)",', line_block):
        keys.add("l1." + k)
        keys.add("l2." + k)
    keys.update(re.findall(r'\{ "([a-zA-Z.]+)",', glob_block))
    return keys


def cpp_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ft, fc = factory_presets()
    presets = [("IN Init", {})] + ft + fc + list(LIBRARY)
    names = [n for n, _ in presets]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise SystemExit(f"duplicate preset names: {sorted(dupes)}")
    keys = valid_keys()
    for n, vals in presets:
        bad = [k for k in vals if k not in keys]
        if bad:
            raise SystemExit(f"{n}: unknown parameter keys {bad}")
    for n, _ in presets:
        if len(n) < 4 or n[2] != " ":
            raise SystemExit(f"preset name needs a two-letter category prefix: {n!r}")

    lines = [
        "// Generated by tools/gen_presets.py -- do not edit.",
        "// Factory tones decoded from docs/reference/cs80_presets.json (spec 05 §3);",
        "// library presets from tools/preset_library.py.",
        '#include "presets/Presets.hpp"',
        "",
        "namespace tannhauser {",
        "",
    ]
    for i, (name, vals) in enumerate(presets):
        if not vals:
            continue
        lines.append(f"static const PresetValue kP{i}[] = {{")
        for k, v in vals.items():
            lines.append(f"    {{ {cpp_string(k)}, {float(v)!r} }},")
        lines.append("};")
    lines.append("")
    lines.append("const BuiltinPreset kBuiltinPresets[] = {")
    for i, (name, vals) in enumerate(presets):
        arr = f"kP{i}" if vals else "nullptr"
        lines.append(f"    {{ {cpp_string(name)}, {arr}, {len(vals)} }},")
    lines.append("};")
    lines.append(f"const int kBuiltinPresetCount = {len(presets)};")
    lines.append("")
    idx = {name: i for i, (name, _) in enumerate(presets)}
    lines.append("const int kFactoryToneIndex[2][11] = {")
    for ch in ("I", "II"):
        lines.append("    { " + ", ".join(str(idx[f"FT {n}"]) for n in CHANNEL_TONES[ch]) + " },")
    lines.append("};")
    lines.append("const char* const kFactoryToneNames[2][11] = {")
    for ch in ("I", "II"):
        lines.append("    { " + ", ".join(cpp_string(n) for n in CHANNEL_TONES[ch]) + " },")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace tannhauser")
    out = ROOT / "src/presets/PresetData.cpp"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(presets)} presets)")


if __name__ == "__main__":
    main()
